puts "deleting DB"
Power.delete_all

puts "Creating new powers"

superpower = [
              "Regenerative Healing Factor",
              "Adoptive Muscle Memory",
              "Body Part Substitution",
              "Anatomical Liberation",
              "Additional Limbs",
              "Organic Constructs",
              "Deflection",
              "Replication",
              "Invisibility",
              "Matter Ingestion",
              "Amalgamation",
              "Plant Merging",
              "Solid Merging ",
              "Wallcrawling",
              "Invulnerability",
              "Immutability ",
              "Mobile Invulnerability",
              "Needle Projection",
              "Immobility",
              "Camouflage",
              "Bone Manipulation",
              "Self-Detonation",
              "Jet Propulsion",
              "Helicopter Propulsion",
              "Cyclone Spinning",
              "Prehensile Hair",
              "Prehensile Tail",
              "Prehensile Tongue",
              "Nail Manipulation",
              "Sharp Tail",
              "Fang Retraction",
              "Spike Protrusion",
              "Structure Weakening",
              "Tentacle Extension",
              "Tendril Generation ",
              "Claw Retraction",
              "Vampire Physiology",
              "Fat Manipulation",
              "Muscle Manipulation ",
              "Fire Generation",
              "Dust Generation",
              "Powder Generation ",
              "Fog Generation",
              "Goo Generation",
              "Heat Generation",
              "Poison Generation",
              "Web Generation",
              "Acid Generation",
              "Water Generation",
              "Bubble Generation",
              "Ink Generation",
              "Ash Generation",
              "Smoke Generation",
              "Stench Generation",
              "Miasma Emission",
              "Nerve Gas Generation",
              "Chlorine Gas Generation",
              "Poison Gas Generation ",
              "Oil Generation",
              "Pheromone Manipulation",
              "Sonic Scream",
              "Echolocation",
              "Enhanced Breath",
              "Fire Breath",
              "Scald Generation ",
              "Vacuum Adaptation",
              "Atmospheric Adaptation",
              "Environmental Adaptation",
              "Aerial Adaptation",
              "Desert Adaptation",
              "Arctic Adaptation",
              "Mountain Adaptation",
              "Subterranean Adaptation",
              "Urban Adaptation",
              "Wetland Adaptation",
              "Fallout Adaptation ",
              "Aquatic Respiration",
              "Self-Sustenance",
              "Reactive Adaptation",
              "Poison Immunity",
              "Thermal Resistance",
              "Tracking Evasion ",
              "Enhanced Strength",
              "Enhanced Condition",
              "Enhanced Combat",
              "Enhanced Agility",
              "Enhanced Leap",
              "Enhanced Bite",
              "Enhanced Durability",
              "Enhanced Dexterity",
              "Enhanced Reflexes",
              "Enhanced Flexibility",
              "Enhanced Lung Capacity",
              "Enhanced Senses",
              "Enhanced Smell",
              "Enhanced Touch",
              "Enhanced Taste",
              "Enhanced Hearing",
              "Enhanced Vision",
              "Enhanced Synesthesia",
              "Hyper Awareness ",
              "Enhanced Accuracy",
              "Enhanced Swordsmanship",
              "Enhanced Crafting",
              "Enhanced Visibility",
              "Enhanced Thievery ",
              "Supernatural Strength",
              "Supernatural Condition",
              "Supernatural Combat",
              "Supernatural Agility",
              "Supernatural Leap",
              "Supernatural Durability",
              "Supernatural Dexterity",
              "Supernatural Reflexes",
              "Supernatural Flexibility",
              "Supernatural Senses",
              "Supernatural Hearing",
              "Supernatural Smell",
              "Supernatural Taste",
              "Supernatural Touch",
              "Supernatural Vision ",
              "Supernatural Accuracy",
              "Supernatural Swordsmanship",
              "Supernatural Thievery ",
              "Vision Faculty",
              "Enhanced Vision",
              "360-Degree Vision",
              "Astral Vision",
              "Atomic Vision",
              "Aura Vision",
              "Chemo Vision",
              "Death Vision",
              "Emotion Vision",
              "Energy Vision",
              "Freeze Vision",
              "Heat Vision",
              "Infrared Vision",
              "Life Vision",
              "Microscopic Vision",
              "Multiple Vision",
              "Night Vision",
              "Probability Vision",
              "Supercolor Vision",
              "Telescopic Vision",
              "Ultraviolet Vision",
              "X-Ray Vision ",
              "Mentality-based Powers",
              "Intuitive Aptitude",
              "Omnilingualism",
              "Botanical Communication",
              "Cyber Communication",
              "Extraterrestrial Communication",
              "Faunal Communication",
              "Fungal Communication ",
              "Ecological Empathy",
              "Enhanced Intelligence",
              "Supernatural Intelligence ",
              "Enhanced Wits",
              "Supernatural Wits ",
              "Psychic Navigation",
              "Eidetic Memory",
              "Knowledge Replication",
              "Psychic Shield",
              "Technopathy",
              "Feral Mind",
              "Dual Mind",
              "4th Wall Awareness",
              "Mentifery",
              "Omniscience",
              "Astral Projection",
              "Mental Projection",
              "Dimensional Awareness",
              "Empathy",
              "Mediumship",
              "Psychometry",
              "Telepathy",
              "Precognition",
              "Oneiromancy",
              "Premonition",
              "Astrological Divination",
              "Numerology",
              "Abacomancy ",
              "Extrasensory Perception",
              "Claircognizance",
              "Retrocognition",
              "Danger Intuition",
              "Clairvoyance",
              "Mendacity Detection",
              "Offspring Detection ",
              "Astral Imprisonment",
              "Hypnosis",
              "Memory Manipulation",
              "Mental Manipulation",
              "Empathic Manipulation",
              "Mind Control",
              "Psychic Persuasion",
              "Belief Induction ",
              "Possession",
              "Astral Possession ",
              "Psionic Inundation",
              "Psionic Projection",
              "Mindscape Transportation",
              "Dream Manipulation",
              "Fear Inducement",
              "Yin & Yang Shift",
              "Furtive Assimilation",
              "Neurocognitive Deficit",
              "Psionic Equilibrium Distortion",
              "Siren Song ",
              "Intangibility",
              "Self-Spawn",
              "Animation",
              "Artistry Animation ",
              "Disintegration",
              "Melting",
              "Dehydration",
              "Petrification",
              "Deoxygenation",
              "Induced Healing",
              "Physical Restoration",
              "Induced Sedation",
              "Induced Paralysis",
              "Death Inducement",
              "Mind Exchange",
              "Induced Ferity",
              "Cloaking",
              "Activation & Deactivation",
              "Access and Occlusion",
              "Dimensional Storage",
              "Psionic Imprinting",
              "Vitality Absorption ",
              "Fundamental Forces",
              "Telekinesis",
              "Physics Manipulation",
              "Light Manipulation",
              "Color Manipulation",
              "Rainbow Colors ",
              "Darkness Manipulation",
              "Nothingness Manipulation",
              "Density Control",
              "Mass Manipulation",
              "Weight Manipulation",
              "Elemental Transmutation",
              "Gravitational Manipulation",
              "Pressure Manipulation",
              "Magnetism Manipulation",
              "Molecular Manipulation",
              "Solar Manipulation",
              "Cosmic Manipulation",
              "Lunar Manipulation",
              "Aura Manipulation",
              "Probability Manipulation",
              "Reality Warping",
              "Sound Manipulation",
              "Temporal Manipulation",
              "Spatial Manipulation",
              "Biological Manipulation",
              "Age Manipulation",
              "Corpse Manipulation",
              "Nerve Manipulation",
              "Jactitation",
              "Fundamental Forces Manipulation ",
              "Literary Manipulation",
              "Mirror Manipulation",
              "Ink Manipulation",
              "Oil Manipulation",
              "Season Manipulation",
              "Circadian Control",
              "Vector Manipulation ",
              "Air Manipulation",
              "Smoke Manipulation ",
              "Earth Manipulation",
              "Crystal Manipulation",
              "Magma Manipulation",
              "Metal Manipulation",
              "Glass Manipulation",
              "Sand Manipulation ",
              "Fire Manipulation",
              "Water Manipulation",
              "Vapor Manipulation ",
              "Ice Manipulation",
              "Electricity Manipulation",
              "Electromagnetic Manipulation",
              "Plant Manipulation",
              "Plant Growth",
              "Wood Manipulation",
              "Fungus Manipulation",
              "Paper Manipulation",
              "Pollen Manipulation",
              "Flower Manipulation",
              "Fruit/Vegetable Manipulation",
              "Nature Manipulation ",
              "Animal Manipulation",
              "Avian Manipulation",
              "Insect Manipulation",
              "Mammal Manipulation",
              "Reptile Manipulation",
              "Fish Manipulation",
              "Arachnid Manipulation",
              "Amphibian Manipulation ",
              "Weather Manipulation",
              "Cloud Manipulation",
              "Storm Manipulation ",
              "Dust Manipulation",
              "Ash Manipulation ",
              "Energy Manipulation",
              "Energy Absorption",
              "Energy Emission ",
              "Concussion Beams",
              "Transitional Phasing Beam ",
              "Microwave Emission",
              "Vibration Emission",
              "Volatile Constructs",
              "Light Generation",
              "Life-Force Manipulation",
              "Radiation Manipulation",
              "Kinetic-Energy Manipulation",
              "Energy Conversion",
              "Energy Constructs",
              "Force-Field Generation",
              "Induced Combustion",
              "Energy Negation ",
              "Dimensional Transportation",
              "Electrical Transportation",
              "Portal Creation",
              "Summoning",
              "Beacon Emission",
              "Super Speed",
              "Teleportation",
              "Time Travel",
              "Escape Artistry",
              "Burrowing",
              "Speed Swimming",
              "Cosmic Teleportation",
              "Wormhole Creation ",
              "Flight",
              "Levitation",
              "Wing Manifestation",
              "Gliding ",
              "Self-Detonation",
              "Self-Ability Bestowal",
              "Self-Disintegration",
              "Self-Molecular Manipulation",
              "Self-Sustenance",
              "Supernatural Self-Preservation",
              "Self-Spawn",
              "Self-Existence",
              "Self-Immortality",
              "Self Origin Manipulation",
              "Higher Consciousness",
              "Self-Transcendence ",
              "Illusion Manipulation",
              "Holographic Projection ",
              "Mimicry",
              "Shapeshifting",
              "Shapeshifting",
              "Malleable Anatomy",
              "Animal Morphing",
              "Size Manipulation",
              "Age Shifting",
              "Elasticity",
              "Air Mimicry",
              "Water Mimicry",
              "Dermal Armor",
              "Bionic Physiology",
              "Monster Physiology",
              "Reactive Adaptation",
              "Power Replication ",
              "Elemental Mimicry",
              "Darkness Mimicry",
              "Metal Mimicry",
              "Gold Mimicry ",
              "Inorganic Mimicry",
              "Fire Mimicry",
              "Magma Mimicry",
              "Air Mimicry",
              "Sand Mimicry",
              "Ink Mimicry",
              "Elemental Mimicry",
              "Clay Mimicry",
              "Slime Mimicry",
              "Smoke Mimicry",
              "Electricity Mimicry",
              "Crystal Mimicry",
              "Diamond Mimicry",
              "Paper Mimicry",
              "Digital Form",
              "Tachyon Mimicry",
              "Electromagnetic Wave Physiology",
              "Ice Mimicry",
              "Stellar Physiology",
              "Spatial Mimicry",
              "Artificially Enhanced Physiology",
              "Energy Physiology",
              "Dust Mimicry",
              "Ash Mimicry ",
              "Organic Mimicry",
              "Animal Morphing",
              "Avian Physiology",
              "Corvid Physiology",
              "Owl Physiology",
              "Parrot Physiology ",
              "Arachnid Physiology",
              "Scorpion Physiology",
              "Spider Physiology ",
              "Insect Physiology",
              "Bee Physiology",
              "Butterfly Physiology",
              "Moth Physiology",
              "Ant Physiology",
              "Beetle Physiology",
              "Blattodea Physiology ",
              "Fish Physiology",
              "Shark Physiology ",
              "Amphibian Physiology",
              "Cephalopod Physiology",
              "Cnidarian Physiology",
              "Crustacean Physiology",
              "Echinoderm Physiology",
              "Parasite Physiology",
              "Reptilian Physiology",
              "Turtle Physiology",
              "Tortoise Physiology",
              "Dinosaur Physiology",
              "Pterosaur Physiology",
              "Snake Physiology",
              "Dragon Physiology ",
              "Mammalian Physiology",
              "Canine Physiology",
              "Feline Physiology",
              "Pro-Simian Mimicry",
              "Bat Physiology",
              "Ursine Physiology",
              "Giraffe Physiology",
              "Camelid Physiology",
              "Rhinoceros Physiology",
              "Elephant Physiology",
              "Equid Physiology",
              "Horse Physiology ",
              "Lagomorph Physiology",
              "Cervid Physiology",
              "Rodent Physiology",
              "Cetacean Physiology",
              "Bovine Physiology",
              "Hyena Physiology",
              "Marsupial Physiology",
              "Pinniped Physiology",
              "Primate Physiology",
              "Sirenia Physiology",
              "Xenarthra Physiology",
              "Monotreme Physiology",
              "Mongoose Physiology",
              "Viverrid Mimicry",
              "Procyonid Physiology ",
              "Plant Mimicry",
              "Wood Mimicry",
              "Floral Mimicry",
              "Fructo Mimicry",
              "Fungal Mimicry ",
              "Unicellular Mimicry",
              "Mythic Physiology",
              "Alien Physiology",
              "Angel Physiology",
              "Faery Physiology",
              "Demon Physiology",
              "Ghost Physiology",
              "Vampire Physiology",
              "Werewolf Physiology",
              "Gorgon Physiology",
              "Phoenix Physiology",
              "Kitsune Physiology",
              "Raiju Physiology",
              "Thunderbird Physiology",
              "Unicorn Physiology",
              "Troll Physiology",
              "Pegasus Physiology",
              "Griffin Physiology",
              "Naga Physiology",
              "Genie Physiology",
              "Wendigo Physiology",
              "Minotaur Physiology",
              "Oni Physiology",
              "Tengu Physiology",
              "Monster Physiology",
              "Nephilim Physiology",
              "Elven Physiology",
              "Bakeneko Physiology",
              "Grim Reaper Physiology",
              "Merfolk Physiology",
              "Gargoyle Physiology",
              "Succubus Physiology",
              "Undead Physiology",
              "Spirit Physiology",
              "Giant Physiology",
              "Sasquatch Physiology",
              "Transcendent Physiology",
              "Hellhound Physiology ",
              "Transcendent Physiology",
              "Cthulhu Mythos Deity Physiology",
              "Cosmic Entity Physiology",
              "Mythic Physiology",
              "Aboriginal Deity Physiology",
              "African Deity Physiology",
              "Altaic Deity Physiology",
              "Armenian Deity Physiology",
              "Arab Deity Physiology",
              "Aztec Deity Physiology",
              "Canaanite Deity Physiology",
              "Celtic Deity Physiology",
              "Chinese Deity Physiology",
              "Egyptian Deity Physiology",
              "Finnish Deity Physiology",
              "Greek Deity Physiology",
              "Protogenoi Physiology",
              "Titan Physiology ",
              "Guarani Deity Physiology",
              "Hindu Deity Physiology",
              "Inca Deity Physiology",
              "Mayan Deity Physiology",
              "Mesopotamian Deity Physiology",
              "Native American Deity Physiology",
              "Norse Deity Physiology",
              "Oceanic Deity Physiology",
              "Orisha Physiology",
              "Philippine Deity Physiology",
              "Roman Deity Physiology",
              "Shinto Deity Physiology",
              "Siberian Deity Physiology",
              "Slavic Deity Physiology",
              "Vodou Deity Physiology",
              "Zoroastrian Deity Physiology ",
              "Chimerism",
              "Hybrid Soul ",
              "Other Mimicry",
              "Candy Mimicry",
              "Garbage Mimicry",
              "Flat Body",
              "Swamp Mimicry",
              "Spring Form",
              "Power Inheritance",
              "Computer Virus Physiology",
              "Bionic Physiology",
              "Roboticization ",
              "Storybook Mimicry",
              "Empathic Mimicry ",
              "Divine",
              "Immortality",
              "Creation",
              "Life Creation",
              "Ability Creation",
              "Animal Creation ",
              "Cosmic Telepathy",
              "Omniscience",
              "Omnipresence",
              "Omnipotence",
              "Omnilock",
              "Magic",
              "Alchemy",
              "Astrology",
              "Chaos Magic",
              "Creation Magic",
              "Dark Arts",
              "Destruction Magic",
              "Divination",
              "Druidic Magic",
              "Elemental Magic",
              "Healing",
              "Illusionary Magic",
              "Life Magic",
              "Mysticism",
              "Necromancy",
              "Shamanism",
              "Spell Casting",
              "Transmutation",
              "Voodoo",
              "White Arts",
              "Craft Magic",
              "Art Magic",
              "Bardic Magic",
              "Sorcery",
              "Occultism",
              "Gnosticism",
              "Ceremonialism",
              "Ritualism",
              "Witchcraft",
              "Witchery",
              "Wizardry",
              "Cures",
              "Charms",
              "Hexes",
              "Jinxes",
              "Tantra",
              "Theurgy",
              "Thaumaturgy",
              "Purification Capabilities ",
              "Universal Irreversibility",
              "Plasma Manipulation",
              "Spatial Manipulation",
              "Spatial-Temporal Lock",
              "Dark Matter Manipulation",
              "Antimatter Manipulation",
              "Alchemy",
              "Complete Arsenal",
              "Chaos Manipulation",
              "Enigma Force",
              "Evolution",
              "Hell-Fire Manipulation",
              "Infinite Supply",
              "Life-Force Manipulation",
              "Life-Force Generation ",
              "Logic Manipulation",
              "Matter Manipulation",
              "Matter Transmutation ",
              "Molecular Manipulation",
              "Power Mixture",
              "Order Manipulation",
              "Paradox Inducement",
              "Pathifery",
              "Physics Manipulation",
              "Mathematics Manipulation",
              "Quantum Manipulation",
              "Summoning",
              "Superpower Manipulation",
              "Terrain Manipulation",
              "Existential Plane Manipulation",
              "Twilight Manipulation",
              "Vocifery"
              ]

superpower.each do |power|
  Power.create!(name: power)
end

puts "Super power created"
